apiVersion: v1
kind: Secret
metadata:
    name: proclone-secrets
type: Opaque
stringData:
    LDAP_SERVER: your.domain.controller
    PC_PORT: "8080"
    SECRET_KEY: placeholder
    LDAP_BIND_DN: cn=ldap-reader,ou=users,dc=domain,dc=com
    LDAP_BIND_PASSWORD: placeholder
    LDAP_BASE_DN: dc=domain,dc=com
