apiVersion: v1
kind: Secret
metadata:
    name: proclone-secrets
type: Opaque
stringData:
    LDAP_SERVER: your.domain.controller
    PC_PORT: "8080"
    SECRET_KEY: placeholder
    LDAP_BIND_DN: cn=ldap-reader,cn=users,dc=domain,dc=com
    LDAP_BIND_PASSWORD: placeholder
    LDAP_BASE_DN: dc=domain,dc=com
    PROX_SVC_USER: placeholder
    PROX_SVC_PASSWORD: placeholder
    PROXMOX_SERVER: your.domain.com
    PROXMOX_PORT: "8006"
