apiVersion: v1
kind: Service
metadata:
  name: proclone-backend
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: proclone-backend
  type: ClusterIP
  internalTrafficPolicy: Cluster
